[package]
name = "load_balancer"
version = "0.1.0"
edition = "2018"


[dependencies]
clap = "3.2.17"
tokio = { version = "1", features = ["full"] }
[[bin]]
name = "load_balancer"
path = "load_balancer.rs"
