version: '3.8'

services:
  rust_build:
    build: .
    platform: "linux/amd64"
    environment:
      - RUST_LOG=debug
    restart: unless-stopped
    volumes:
      - .:/usr/src/myapp
    command: 'cargo build --target x86_64-unknown-linux-gnu --release '
#    command: 'tail -f /dev/null'
